export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const ORDER_PURCHASE_SUCCCESS = "ORDER_PURCHASE_SUCCCESS";
export const ORDER_PURCHASE_FAILED = "ORDER_PURCHASE_FAILED";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const FETCH_TIME_TABLE_START = "FETCH_TIME_TABLE_START";
export const FETCH_TIME_TABLE_SUCCESS = "FETCH_TIME_TABLE_SUCCESS";
export const FETCH_TIME_TABLE_FAIL = "FETCH_TIME_TABLE_FAIL";

export const SCHEDULE_REDIRECT_PATH = "SCHEDULE_REDIRECT_PATH";

//get USER profile
export const FETCH_USER_PROFILE_START = "FETCH_USER_PROFILE_START";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAIL = "FETCH_USER_PROFILE_FAIL";

//get USER address
export const FETCH_USER_ADDRESS_START = "FETCH_USER_ADDRESS_START";
export const FETCH_USER_ADDRESS_SUCCESS = "FETCH_USER_ADDRESS_SUCCESS";
export const FETCH_USER_ADDRESS_FAIL = "FETCH_USER_ADDRESS_FAIL";

//delete USER address
export const DELETE_USER_ADDRESS_START = "DELETE_USER_ADDRESS_START";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_FAIL = "DELETE_USER_ADDRESS_FAIL";

//update USER address
export const UPDATE_USER_ADDRESS_START = "UPDATE_USER_ADDRESS_START";
export const UPDATE_USER_ADDRESS_SUCCESS = "UPDATE_USER_ADDRESS_SUCCESS";
export const UPDATE_USER_ADDRESS_FAIL = "UPDATE_USER_ADDRESS_FAIL";

//add USER address
export const ADD_USER_ADDRESS_START = "ADD_USER_ADDRESS_START";
export const ADD_USER_ADDRESS_SUCCESS = "ADD_USER_ADDRESS_SUCCESS";
export const ADD_USER_ADDRESS_FAIL = "ADD_USER_ADDRESS_FAIL";
